### ISSUE TITLE
Add preview for sharing dragonfly.co.nz on social media

### ISSUE THREAD

**Issue by mathematiguy** [dragonfly-science/dragonfly-website#111]
I've been sharing dragonfly.co.nz around a bit on social media, and noticed that the site could probably use some stuff added to the head tag to make it look a little tidier.

From digging through the github repo, it looks like dragonfly-website/content/templates/default.html is where the edit needs to go.

Refer to the image below:
![image](https://user-images.githubusercontent.com/11322313/39672121-2fbcf632-5178-11e8-99f2-291b1c0d07cc.png)

I'll be happy to attempt a pull request myself to solve the problem if noone else has time.

Relevant stackoverflow: https://stackoverflow.com/questions/19632323/default-website-image-for-social-sharing

Relevant social media best practices: https://developers.facebook.com/docs/sharing/best-practices

Cheers,

Caleb

**Comment by edwardabraham** [comment]
Thanks to @finlay ,  this has been fixed. You can now add 'og-description' and 'og-title' tags to the metadata of posts and pages to customize how they seen.  Facebook posts can be previewed here: https://developers.facebook.com/tools/debug/
