### ISSUE TITLE
Dead url in dragonfly-website/content/work/webrear-case-study/content.md

### ISSUE THREAD

**Issue by mathematiguy** [dragonfly-science/dragonfly-website#114]
Unfortunately, the url marked 'Explore New Zealand’s regional economies here' now raises a 404 error on MBIE's website.

![image](https://user-images.githubusercontent.com/11322313/40232882-cd239c84-5af4-11e8-9aa4-8b554ce65851.png)

Fortunately, it looks like the visualisation has been migrated here: http://webrear.mbie.govt.nz/summary/new-zealand

![image](https://user-images.githubusercontent.com/11322313/40232934-01f68908-5af5-11e8-9784-5236ed37559a.png)

But I'm not sure if this is exactly the app that Dragonfly developed. It might be worth someone else confirming this before fixing the link.

**Comment by finlay** [comment]
Thanks Caleb

I will fix that ....
