### ISSUE TITLE
Summary paragraph missing from publications

### ISSUE THREAD

**Issue by edwardabraham** [dragonfly-science/dragonfly-website#124]
There is a bug in processing the summary for publications. It doesn't show up if it is only a single paragraph. Make sure that the summary is split into two or more paragraphs and it will then appear.

**Comment by katrin-berkenbusch** [comment]
thanks, I'd forgotten about this aspect.

**Comment by katrin-berkenbusch** [comment]
I am doing that, but am having no luck with the summaries showing up.

**Comment by edwardabraham** [comment]
They look OK to me?

**Comment by katrin-berkenbusch** [comment]
Sorry, I wasn't specific enough - I can't make the summaries for the three latest publications (by Iggy) show up:
menzies_leaf_2016,
menzies_temporal_2010,
cooney_red_2012.

**Comment by katrin-berkenbusch** [comment]
prevented by the bullet point list in the summary, to be raised as a separate issue.
