### ISSUE TITLE
keeping the search page for going backwards on the publications page

### ISSUE THREAD

**Issue by katrin-berkenbusch** [dragonfly-science/dragonfly-website#179]
Currently, when I look up the publications of a Dragonfly author, I lose the search when I click on a link to "read more" and then go back to look at other papers by the same author. 

It's a minor issue, but annoying if someone wants to keep looking at other papers by the same author they are interested in.

**Comment by simonwinter** [comment]
Hi @katrin-berkenbusch - I think we've resolved this in the new site: http://dragonfly-website-staging.dragonfly-science.reports.dragonfly.co.nz/publications/

Can you see if that fixes what you're after?

**Comment by katrin-berkenbusch** [comment]
Yes, that’s great. 
Thank you.
