### ISSUE TITLE
Content requirements

### ISSUE THREAD

**Issue by simonwinter** [dragonfly-science/dragonfly-website#209]
**Description:**

This issue lists all the known content based issue that we need to address.

---

**Issues:**

- Images (issue #208) _reviewing & supply of updated imagery_
- Home page (issue #207) _structural changes + new content_
- Data page (issue #206) _moving contents to news pages/deleting page_
- Case studies (issue #205) _creating new case studies_
- What we do (issue #204) _creating content_
- Who we are (issue #203) _creating content_

**Comment by simonwinter** [comment]
This is the latest design review from Pep:

[Uploading Dragonfly_Website_review_Dec2020.pdf…]()

**Comment by edwardabraham** [comment]
Thanks very much @simonwinter :+1:
