### ISSUE TITLE
Lost up arrow

### ISSUE THREAD

**Issue by edwardabraham** [dragonfly-science/dragonfly-website#233]
Can't escape the "contact details" because the up arrow is too far up my page, and there is no scroll bar ... (I can just see the tail of the arrow if I squint)
![Screenshot from 2021-06-29 16-19-47](https://user-images.githubusercontent.com/120982/123736910-250b8b00-d8f6-11eb-9e40-757a2c42e5e9.png)

**Comment by simonwinter** [comment]
Yes, the footer is currently a bit mangled. On the list to fix!
