### ISSUE TITLE
Recreational fisheries

### ISSUE THREAD

**Issue by edwardabraham** [dragonfly-science/dragonfly-website#272]
* The recreational fisheries report is included twice. Can we remove the old draft report and link to the published report only
* Also, can we add in a summary so that we get a page that we can click through to.

**Comment by katrin-berkenbusch** [comment]
Yes, that sounds good, I’ll update it.

**Comment by katrin-berkenbusch** [comment]
It’s there twice, because one is the TWG presentation, the other is the draft report. I will update the latter to the final report, with a summary.

**Comment by edwardabraham** [comment]
Thanks!
