### ISSUE TITLE
Selection no preserved of reference list

### ISSUE THREAD

**Issue by yvanrichard** [dragonfly-science/dragonfly-website#28]
When selecting a tag from the drop-down selectors, it would be nice after clicking the details of a publication to come back to the same selection. At the moment, after coming back, the selected term(s) stay in the selection box, but the list is back to the whole lot, losing the selection.

**Comment by edwardabraham** [comment]
Good point.  State management. Will check with @vizowl. Maybe it is best to
put the tags into the URL.

On 3 August 2015 at 13:08, Yvan Richard <notifications@github.com> wrote:

> When selecting a tag from the drop-down selectors, it would be nice after
> clicking the details of a publication to come back to the same selection.
> At the moment, after coming back, the selected term(s) stay in the
> selection box, but the list is back to the whole lot, losing the selection.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dragonfly-science/website/issues/28>.
>



-- 

Edward Abraham
www.dragonfly.co.nz
Dragonfly Science, PO Box 27535, Wellington 6141, New Zealand
Level 5, 158 Victoria Street, Te Aro, Wellington
M: +64 21 989 454
T: +64 4 385 9285
