### ISSUE TITLE
disappearing publications?

### ISSUE THREAD

**Issue by katrin-berkenbusch** [dragonfly-science/dragonfly-website#329]
Some of our publications seem to have disappeared (from 2021, and possible 2022?). I get directed to them on the Dragonfly website when I google the title, but they are not listed under Publications.

Here is an example - 
Bivalve abundance in relation to sediment properties across northern North Island. 
New Zealand Fisheries Assessment Report 2021/49

P. Neubauer,
D. Damodaran,
K. Berkenbusch

This FAR should be under 2021 on the publications pages, but it's not.
When I google the title, I get to this site - https://www.dragonfly.co.nz/publications/neubauer_bivalve_2021.html.

It also doesn't come up when I put the title into our Search function on Publications.

**Comment by simonwinter** [comment]
Hi @katrin-berkenbusch - this looks to me like the website needs to update the bibliography submodule. An easy enough task - will make some time this week.

**Comment by simonwinter** [comment]
tHis should be resolved now @katrin-berkenbusch! Please close if you think it is 🤞

**Comment by katrin-berkenbusch** [comment]
Thanks, I’ll have a look.
Is there a way to prevent it happening again?

**Comment by katrin-berkenbusch** [comment]
Thank you,

**Comment by simonwinter** [comment]
hmm - it's a problem with submodules being out of sync with the main repo. It can be tricky to solve ...

What we could do is set up another gorby job that simply provides the latest .bib file to the website job - from the master branch of the bibliography repo. That would be the best way to guarantee that when gorby runs the website job, we always get the up to date bib file 🤷 

I will add an issue :)

**Comment by katrin-berkenbusch** [comment]
Thank you, that sounds good.
