### ISSUE TITLE
Image sizes

### ISSUE THREAD

**Issue by edwardabraham** [dragonfly-science/dragonfly-website#33]
Check that images are scaled appropriately, depending on the media query. At the moment there are many large images through the site, and we need a resizing mechanism in Hakyll.

e.g., https://github.com/thsutton/hakyll-banner-images-demo

**Comment by finlay** [comment]
Added support for producing image transforms in 
https://github.com/dragonfly-science/website/commit/e92b4315c4

Should be straight forward to add more sizes. See this documentation to find out about setting size:
http://www.imagemagick.org/script/command-line-processing.php#geometry

**Comment by edwardabraham** [comment]
I have applied this to the images on the home page, and to the teaser images. I haven't handled the banner images on the people pages or on the case studies yet. These will still be large.

**Comment by edwardabraham** [comment]
Hmm. The small images are being produced, but they aren't being used in the templates yet. Not sure why!
