### ISSUE TITLE
Refactor bib -> website pipeline

### ISSUE THREAD

**Issue by simonwinter** [dragonfly-science/dragonfly-website#333]
On occasions, the checked out bibliography repo is out of date when we build the website. To ensure integrity we should have a separate bib job that provides the most recent bibliography to the uat & prod website gorby jobs (will require adding a similar process to dev env).

Note for @simonwinter - use the set up we used for RSI

**Comment by katrin-berkenbusch** [comment]
Several publications have again disappeared from the website, see also dragonfly-science/dragonfly-website#329.

**Comment by simonwinter** [comment]
@katrin-berkenbusch I bumped the bib sub module again, so hopefully it's up to date now?

**Comment by katrin-berkenbusch** [comment]
The publications were up-to-date, but some of the recent ones have disappeared again. From a quick check it looks like several in 2021 and the 2022 ones.
Can you please bump the submodule again @simonwinter ?
