### ISSUE TITLE
Blank tiles in publications results

### ISSUE THREAD

**Issue by yvanrichard** [dragonfly-science/dragonfly-website#342]
I just searched for "risk" on the publications page and there's a bunch of empty tiles at the end of the results.

![image](https://user-images.githubusercontent.com/1634845/176045667-4be6a4ad-f7c8-4a81-98df-86857799ca60.png)

I don't have time to figure out why, but they link to pdf reports, from different years.

**Comment by katrin-berkenbusch** [comment]
Yep,

That may be part of the “disappearing publications” problem? 
All the reports from the SHSRA should be there, amongst other publications that have disappeared too.
