### ISSUE TITLE
Broken link on website: NEFD project

### ISSUE THREAD

**Issue by RABurson** [dragonfly-science/dragonfly-website#380]
Link to download report on https://www.dragonfly.co.nz/work/NEFD-case-study.html is broken/has limited usability. Takes user to a login page for password-protected location.

**Comment by ignatiusm** [comment]
Thanks @RABurson for raising the issue! :tada: 

@simonwinter correct link should be one of the following:

- [Landing page for report](https://www.mpi.govt.nz/forestry/forest-industry-and-workforce/forestry-wood-processing-data/new-zealand-forest-data/) <- but it is hard to find the NEFD report amongst all the other info.
- [Direct link to report](https://www.mpi.govt.nz/dmsdocument/55996-2022-NEFD-Report) <- this is good, but may break in the future

**Comment by edwardabraham** [comment]
Thanks. Have updated to a direct link to the 2022 report. It just felt more direct, even though it isnt future proofed.
