### ISSUE TITLE
Spelling mistake on news/2022-07-21-kahawai-collective.html

### ISSUE THREAD

**Issue by nokome** [dragonfly-science/dragonfly-website#390]
At https://www.dragonfly.co.nz/news/2022-07-21-kahawai-collective.html, in the banner image, "reproducible" is spelt as "reproducable".

**Comment by edwardabraham** [comment]
Hi @dmiddleton ... could we have an updated copy of the Kahawai Collective banner. Thanks!

**Comment by dmiddleton** [comment]
@edwardabraham as far as I know, the problem image only exists in the article so must have been produced @Dragonfly?

**Comment by sarah-wilcox** [comment]
fixed now - thanks for spotting!

**Comment by sarah-wilcox** [comment]
done
