### ISSUE TITLE
Protected species data link broken

### ISSUE THREAD

**Issue by ignatiusm** [dragonfly-science/dragonfly-website#391]
![image](https://github.com/dragonfly-science/dragonfly-website/assets/11403879/69987a49-0f54-4813-8eaa-4b629362af3a)

White chinned petrel link in [protected species data](https://www.dragonfly.co.nz/work/protected-species-data.html) page is broken. I suspect these data are no longer available given Abacus looked after the most recent estimates.

**Comment by Philipp-Neubauer** [comment]
Does the access data link still work?

**Comment by simonwinter** [comment]
Looks like it's changed from:

https://protectedspeciescaptures.nz/PSCv5a/released/white-chinned-petrel/trawl/all-vessels/eez/2018-19/

to:

https://protectedspeciescaptures.nz/PSCv6/released/white-chinned-petrel/trawl/all-vessels/eez/2018-19/

I don't have much experience with PSC - does that look sensible @Philipp-Neubauer?

**Comment by edwardabraham** [comment]
Thanks @ignatiusm ... have updated the link.
