### ISSUE TITLE
pull requests

### ISSUE THREAD

**Issue by katrin-berkenbusch** [dragonfly-science/dragonfly-website#416]
Is there a way to get the pull requests actioned more quickly? @edwardabraham

**Comment by edwardabraham** [comment]
Yes, the secret is that you need to tell me! Unfortunately, I seem to get a vast number of emails from Github about a whole range of irrelevant things. So, I tend not to read  them.

**Comment by edwardabraham** [comment]
For example, haphazardly browsing here is the first time that i have seen this issue :)
