### ISSUE TITLE
Missing project team member

### ISSUE THREAD

**Issue by ignatiusm** [dragonfly-science/dragonfly-website#433]
In the [thematic analysis case study](https://www.dragonfly.co.nz/work/thematic-analysis-case-study.html), Emma is highlighted by the client as having played a critical role. Emma isn't listed as part of the project team (see screenshot below).

![image](https://github.com/user-attachments/assets/791a877a-8495-41da-b44c-80546678b43b)

**Comment by katrin-berkenbusch** [comment]
Good catch, thank you @ignatiusm
