### ISSUE TITLE
Line height on the menu dropdown

### ISSUE THREAD

**Issue by edwardabraham** [dragonfly-science/dragonfly-website#46]
Doesn't all fit on my mobile screen ...

**Comment by edwardabraham** [comment]
Fix this at the same time as #43

**Comment by edwardabraham** [comment]
Drop down has a few issues on mobile menus:
1. Can slide the page through the menu
2. Text size means that not all the text fits on reasonably sized screens
3. Drag goes to the page below

Maybe you could look at these @thomasin-abraham?

**Comment by thomasin-abraham** [comment]
It fits on My screen am I not reasonably sized):
