### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by edwardabraham** [dragonfly-science/dragonfly-website#50]
Need to give the site some SEO love!
1. Each page should have a meta description tag. This should be around a tweet in length, and will show up as a summary of the page in places like facebook and in google search.

**Comment by sarah-wilcox** [comment]
Would you like me to help with this one?

**Comment by edwardabraham** [comment]
@sarah-wilcox That would be great. Ask @vizowl how to add meta data to the top of each page.

**Comment by yvanrichard** [comment]
[This StackOverflow post](http://stackoverflow.com/questions/6693499/how-can-i-set-a-website-image-that-will-show-as-preview-on-facebook) might help. Also, the [Facebook "Object Debugger"](https://developers.facebook.com/tools/debug/og/object/) is a good tool to see the look of a share on FB.

**Comment by vizowl** [comment]
It looks like fro each page we need og:title, go:description, go:image.

I suggest that we create a generic title, description and image that we use on every page and then we define the variables og-title, og-description, og-image as additional yaml metadata that can be used on specific pages to override the generic one.

So @sarah-wilcox if you can send me the generic values and edit once post to add the specific versions I will get it working.

BTW to reply on github click the 'view on github' link in the mail and login as sarah-wilcox.

**Comment by sarah-wilcox** [comment]
Not sure I totally get you, but here's some text for INZ case study. We already have title and image...I think.
Using data analysis and predictive modelling, we built an automated system to sort visitor visa applications. 
Popping out for a few mins, back soon.

**Comment by edwardabraham** [comment]
That's right. I think that we can use the teaser image and the teaser to
satisfy this requirement for most of the pages (people, news, case-study)..
We can then write something specific for the home page, and the list pages.
But this should be straightforward once we have the mechanism in place. So
we should probably rescind and say that we don't need @sarah-wilcox to do
anything about this issue yet!


On 16 September 2015 at 14:58, sarah-wilcox <notifications@github.com>
wrote:

> Not sure I totally get you, but here's some text for INZ case study. We
> already have title and image...I think.
> Using data analysis and predictive modelling, we built an automated system
> to sort visitor visa applications.
> Popping out for a few mins, back soon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dragonfly-science/website/issues/50#issuecomment-140610918>
> .
>



-- 

Edward Abraham
www.dragonfly.co.nz
Dragonfly Science, PO Box 27535, Wellington 6141, New Zealand
Level 5, 158 Victoria Street, Te Aro, Wellington
M: +64 21 989 454
T: +64 4 385 9285

**Comment by simonwinter** [comment]
An update on this:

* There is now a social media image (a resized version of the teaser) - which is currently sized at 1200 x 600 (all the social networks have different sizes for posts - this is the current size that should work for all .. though they change each year! - e.g. https://www.godaddy.com/garage/facebook-profile-picture-size-and-more/).
* A page can have a `descripton` and/or an `og-description` tag. This give you flexibility on the content for sharing. If one of those tags is not present, the page will use the other (if present).

This will all be available when the new site is launched.

**Comment by edwardabraham** [comment]
Thanks! Hopefully, Hakyll can generate default images at all the necessary sizes, so the user doesn't need to do this.

**Comment by simonwinter** [comment]
@edwardabraham Hakyll is indeed generating all the sizes for us - so as long as we upload a large enough image, we'll be covered for all the required sizes ;)
