### ISSUE TITLE
Search functionality?

### ISSUE THREAD

**Issue by yvanrichard** [dragonfly-science/dragonfly-website#51]
Is some search functionality planned eventually for the website? I think it would be useful, e.g. to search for all pages/blog posts/news stories featuring a specific topic or person.

**Comment by edwardabraham** [comment]
We have implemented search on the publications, but we could enable search
across all the content in the same way. My issue with website search is
that I never use it (relying on google to do that job better than we can).
Worth a broader discussion.



On 16 September 2015 at 15:34, Yvan Richard <notifications@github.com>
wrote:

> Is some search functionality planned eventually for the website? I think
> it would be useful, e.g. to search for all pages/blog posts/news stories
> featuring a specific topic or person.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dragonfly-science/website/issues/51>.
>



-- 

Edward Abraham
www.dragonfly.co.nz
Dragonfly Science, PO Box 27535, Wellington 6141, New Zealand
Level 5, 158 Victoria Street, Te Aro, Wellington
M: +64 21 989 454
T: +64 4 385 9285

**Comment by yvanrichard** [comment]
Like the search functionality for publications, which is great, the advantage over Google is that it can be tailored, to filter by type (case studies, blog post, news story, etc.), and also presented by type. 
I don't think it's a priority, but the usefulness will increase with more content being added to the website. I personally often use searches inside websites.
