### ISSUE TITLE
editing live site

### ISSUE THREAD

**Issue by sarah-wilcox** [dragonfly-science/dragonfly-website#55]
I have corrections to a page on sublime (<<<<<<head problem on INZ case study page) that I wanted to push to live site. Is the process the same as for staging?

**Comment by edwardabraham** [comment]
Hi Sarah, I don't see that problem on the live site, so I think that someone has already fixed it. You need to pull the latest version before making changes. If you are able to pop in, someone could step you through the git workflow.

**Comment by edwardabraham** [comment]
The staging site (www-dev.dragonfly.co.nz) is updated whenever anyone pushes changes to the github repository. Chris or I can then promote the staging site to seeing the live site when you are happy with it.

**Comment by sarah-wilcox** [comment]
Thanks - I'll probably come by tomorrow for a lesson :-)
