### ISSUE TITLE
trying to fix the spello in Finlay's summary

### ISSUE THREAD

**Issue by katrin-berkenbusch** [dragonfly-science/dragonfly-website#57]
I changed "storying" to "storing" but I can't commit the changes it seems. Or they don't convert onto the website.

**Comment by edwardabraham** [comment]
At the moment there is no automatic updating of the website when you make
changes. @vizowl has this in his queue. When  it is working, changes will
show up at www-dev.dragonfly.co.nz. @vizowl or I need to make a manual
change to switch the website from development to live.

**Comment by edwardabraham** [comment]
Have fixed this. The changes are now live.
