### ISSUE TITLE
Migrate to Firebase

### ISSUE THREAD

**Issue by edwardabraham** [dragonfly-science/dragonfly-website#66]
I have set up a firebase app dflydsci. We need to migrate from divshot, as it will be shut down in December. The migration instructions are here
http://docs.divshot.com/migrate

Will need to tweak deployhub to use the firebase cli, and we will need to change the DNS once it is up and running.

One plus for firebase is that they set up an SSL certificate on our behalf—no need to purchase a cert for this domain :)

**Comment by vizowl** [comment]
https://dflydsci.firebaseapp.com

Now we need to migrate the domain and decide where to host www-dev

**Comment by edwardabraham** [comment]
Should be done as soon as the SSL cert is set up.



    Regards,

Edward Abraham - +64 21 989 454

Dragonfly Data Science
 | Level 5, 158 Victoria StreetPh  +64 4 385 9285 | www.dragonfly.co.nz

**Comment by edwardabraham** [comment]
Have now migrated the site. I will leave the divshot version hanging around, in case the DNS taks a while to propagate. Note that changes pushed to the release branch will now be automatically deployed (and changes to master won't)
