### ISSUE TITLE
add risk assessment reports to publication list

### ISSUE THREAD

**Issue by katrin-berkenbusch** [dragonfly-science/dragonfly-website#78]

**Comment by katrin-berkenbusch** [comment]
2015 risk assessment and supplement

**Comment by katrin-berkenbusch** [comment]
Can't formally assign myself in github, but will include them later on

**Comment by edwardabraham** [comment]
* I have added you as a collaborator. Note that with public repos you can
fork them (which makes a copy in your github account). You can then clone
it form there and make changes. When you are done, you submit a pull
request, which sends all the changes back to the main repository.

**Comment by katrin-berkenbusch** [comment]
Hi Ed,

Does that mean I should go with forking, rather than updating it the way I do with other repos? I can pull but not push my updates.
Cheers,
Katrin

**Comment by edwardabraham** [comment]
No, push away. Have fixed your permissions. If you merge changes into the
release branch they should be deployed to the website after 10 minutes or
so (although this doesn't seem to be working at the moment!).

**Comment by katrin-berkenbusch** [comment]
Even though the main report and the supplement are the same AEBR, should we have the supplementary document listed separately on the website so it can be accessed directly? At the moment, someone would need to know it exists or read to the bottom of the Exec Sum of the main report to find it. Just a thought.

**Comment by edwardabraham** [comment]
yes, I removed it, but I think it was a mistake and that this is a good
idea.

**Comment by katrin-berkenbusch** [comment]
Cool, I'll add it with a separate link.

**Comment by katrin-berkenbusch** [comment]
Now a separate publication.
