### ISSUE TITLE
subject in news story

### ISSUE THREAD

**Issue by katrin-berkenbusch** [dragonfly-science/dragonfly-website#83]
Just a quick query about the use of "Dragonfly" in the news stories:
"...Dragonfly mapped the cadmium content of 1980 soil samples from across New Zealand. They found..."
I am unsure why Dragonfly is referred to as "they".  Dragonfly is the company's name, so subsequent reference to it should be "it". Better still, perhaps change to using individual's names, e.g., "Dragonfly's Edward..." (or something similar) to make the stories more personal?

**Comment by Philipp-Neubauer** [comment]
+1 for using individual names

On Fri, May 20, 2016 at 10:14 AM, katrin-berkenbusch <
notifications@github.com> wrote:

> Just a quick query about the use of "Dragonfly" in the news stories:
> "...Dragonfly mapped the cadmium content of 1980 soil samples from across
> New Zealand. They found..."
> I am unsure why Dragonfly is referred to as "they". Dragonfly is the
> company's name, so subsequent reference to it should be "it". Better still,
> perhaps change to using individual's names, e.g., "Dragonfly's Edward..."
> (or something similar) to make the stories more personal?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/dragonfly-science/dragonfly-website/issues/83>
>



-- 
Phil

**Comment by edwardabraham** [comment]
The style is a little press-releasy, and so has that more formal tone.
Would be awesome to get some that were written from a more personal
perspective.

In the context, I think it clear that the plurality of "they" refers to
staff,  and "it" would sound very weird. 'Edward found' would be fine :)
