### ISSUE TITLE
check the Boulton et al. 2008 ref

### ISSUE THREAD

**Issue by katrin-berkenbusch** [dragonfly-science/dragonfly-website#85]
The capital letters in the title are lower case on the website.

**Comment by edwardabraham** [comment]
You just need to escape the capital letters properly in the bibliography
file.

**Comment by katrin-berkenbusch** [comment]
The entire title is in "{}", does that not take care of it?

**Comment by katrin-berkenbusch** [comment]
It works for "boulton_effect_2010", but not for "boulton2008influence"

**Comment by katrin-berkenbusch** [comment]
OH! double entry of the same reference!
